# Generated by Django 4.2.7 on 2023-11-15 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('brand', models.CharField(max_length=128)),
                ('price', models.IntegerField()),
                ('del_price', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=64)),
                ('views', models.IntegerField(default=0)),
                ('season', models.CharField(max_length=16)),
                ('url', models.TextField(null=True)),
                ('tag', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'style',
            },
        ),
        migrations.CreateModel(
            name='StyleGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outfits.goods')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outfits.style')),
            ],
            options={
                'db_table': 'style_goods',
            },
        ),
    ]
